---
name: Validate composer dependencies

'on':
  pull_request:
    branches:
      - main

  push:
    branches:
      - main

jobs:
  validate-deps:
    name: Validate composer dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4

      - uses: cachix/install-nix-action@v13
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - run: nix-shell --run "make composer-validate"
